config/routes.rb
Rails.application.routes.draw do
  resources :book_reviews
  get 'users/show'
    root 'static_pages#home'
  get 'static_pages/home'
  devise_for :users
    resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_one_attached :image
    has_many :book_review, -> { order "created_at DESC"}
end

app/models/book_review.rb
class BookReview < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
   has_one_attached :avatar

  validates :name, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
     devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age, :avatar]
     devise_parameter_sanitizer.permit :account_update, keys: [:name, :age, :avatar]
    end    
end

app/controllers/book_reviews_controller.rb
class BookReviewsController < ApplicationController
  before_action :set_book_review, only: [:show, :edit, :update, :destroy]

  # GET /book_reviews
  # GET /book_reviews.json
  def index
    @book_reviews = BookReview.all
  end

  # GET /book_reviews/1
  # GET /book_reviews/1.json
  def show
  end

  # GET /book_reviews/new
  def new
    @book_review = BookReview.new
  end

  # GET /book_reviews/1/edit
  def edit
  end

  # POST /book_reviews
  # POST /book_reviews.json
  def create
    @book_review = BookReview.new(book_review_params)
    @book_review.user_id = current_user.id

    respond_to do |format|
      if @book_review.save
        format.html { redirect_to @book_review, notice: 'Book review was successfully created.' }
        format.json { render :show, status: :created, location: @book_review }
      else
        format.html { render :new }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_reviews/1
  # PATCH/PUT /book_reviews/1.json
  def update
    respond_to do |format|
      if @book_review.update(book_review_params)
        format.html { redirect_to @book_review, notice: 'Book review was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_review }
      else
        format.html { render :edit }
        format.json { render json: @book_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_reviews/1
  # DELETE /book_reviews/1.json
  def destroy
    @book_review.destroy
    respond_to do |format|
      format.html { redirect_to book_reviews_url, notice: 'Book review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_review
      @book_review = BookReview.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_review_params
      params.require(:book_review).permit(:user_id, :book_id, :review)
    end
end 

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
       @book_review = BookReview.new
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :number_of_pages, :image, :detail)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
      @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_reviews_helper.rb
module BookReviewsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_reviews/_form.html.erb
<%= form_with(model: book_review, local: true) do |form| %>
  <% if book_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_review.errors.count, "error") %> prohibited this book_review from being saved:</h2>

      <ul>
        <% book_review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.number_field :book_id %>
  </div>

  <div class="field">
    <%= form.label :review %>
    <%= form.text_area :review %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_reviews/edit.html.erb
<h1>Editing Book Review</h1>

<%= render 'form', book_review: @book_review %>

<%= link_to 'Show', @book_review %> |
<%= link_to 'Back', book_reviews_path %>

app/views/book_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Reviews</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_reviews.each do |book_review| %>
      <tr>
        <td><%= book_review.user_id %></td>
        <td><%= book_review.book_id %></td>
        <td><%= book_review.review %></td>
        <td><%= link_to 'Show', book_review %></td>
        <td><%= link_to 'Edit', edit_book_review_path(book_review) %></td>
        <td><%= link_to 'Destroy', book_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Review', new_book_review_path %>

app/views/book_reviews/new.html.erb
<h1>New Book Review</h1>

<%= render 'form', book_review: @book_review %>

<%= link_to 'Back', book_reviews_path %>

app/views/book_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @book_review.user_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @book_review.book_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @book_review.review %>
</p>

<%= link_to 'Edit', edit_book_review_path(@book_review) %> |
<%= link_to 'Back', book_reviews_path %>

app/views/books/_form.html.erb
<div class="card col-sm-6 mx-auto mt-5">
  <div class="card-body">
    <h3 class="mt-1 mb-3">新しい本の追加</h3>
    <%= form_with(model: book, local: true) do |form| %>
    <% if book.errors.any? %>
      <div id="error_explanation">　
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :title, "本のタイトル", :class => "form-label" %>
      <%= form.text_field :title, :class => "form-control" %>
    </div>

<div class="field">
      <%= form.label :number_of_pages, "ページ数", :class => "form-label" %>
      <%= form.number_field :number_of_pages, :class => "form-control" %>
    </div>

    <div class="field">
      <%= form.label :detail, "本の内容", :class => "form-label"  %>
      <%= form.text_area :detail, :class => "form-control"%>
    </div>

    <div class="field">
      <%= form.label :image, "本"  %>
      <%= form.file_field :image %><br>
    </div>
    
    <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>
  </div>
</div><div class="card col-sm-6 mx-auto mt-5">
  <div class="card-body">
    <h3 class="mt-1 mb-3">新しい本の追加</h3>
    <%= form_with(model: book, local: true) do |form| %>
    <% if book.errors.any? %>
      <div id="error_explanation">　
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.label :title, "本のタイトル", :class => "form-label" %>
      <%= form.text_field :title, :class => "form-control" %>
    </div>

    <div class="field">
      <%= form.label :number_of_pages, "ページ数", :class => "form-label" %>
      <%= form.number_field :number_of_pages, :class => "form-control" %>
    </div>

<div class="field">
      <%= form.label :detail, "本の内容", :class => "form-label"  %>
      <%= form.text_area :detail, :class => "form-control"%>
    </div>

    <div class="field">
      <%= form.label :image, "本"  %>
      <%= form.file_field :image %><br>
    </div>
    
      <div class="actions">
      <%= form.submit %>
    </div>
    <% end %>
    
    </div

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<div class="row">
　<% @books.each do |book| %>
　　<div class="col-md-3">
      <div class="card img-thumbnail">
        <% if book.image.attached? %>
          <%= image_tag book.image, class: "card-img" %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= book.title %></h5>
          <p class="card-text text-muted">ページ数：<%= book.number_of_pages %></p>
        </div>
        <div class="card-body">
          <%= button_to "詳細を見る", book, method: :get, class: "btn btn-outline-secondary btn-sm" =%>
        </div>
      </div>
    </div>
  <% end %>
</div>
</br>
<%= button_to "本を追加する", new_book_path, method: :get ,class: "btn btn-primary btn-sm" %>  

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="card mb-3">
        <h3 class="card-header">本詳細</h3>
        <div class="card-body">
          <h5 class="card-title"><%= @book.title %></h5>
          <h6 class="card-subtitle text-muted">ページ数：<%= @book.number_of_pages %></h6>
  　　　　</div>
  　　　　<% if @book.image.attached? %>
          <%= image_tag @book.image, class: "card-img" %>
        <% end %>
        <div class="card-body">
          <p class="card-text"><%= @book.detail %></p>
        </div>
      </div>
    </div>
  <div class="col-sm-4">
    <div class="card bg-light mb-3" style="max-width: 40rem;">
      <div class="card-header">レビュー</div>
      <div class="card-body">
        <ul>
          <% @book.book_review.each do |book_review|%>
          　<div class="card border-light mb-3" style="max-width: 20rem;">
              <div class="card-header"><%= book_review.user.name %></div>
              <div class="card-body">
                <p class="card-text"><%= book_review.review %></p>
              </div>
            </div>
          <% end %>
        </ul>
      <%= form_with(model: @book_review, local: true) do |form| %>
        <div class= "field">
          <%= form.text_area :review, :class => "form-control" %>
          <%= form.hidden_field :book_id, :value => @book.id %>
        </div>
        <div class="actions">
          <%= form.submit %>
        </div>
       <% end %>
       </div>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ourfirstrails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-toggler navbar-dark bg-primary">
      <%= link_to "Book Review", root_path, class: "nav-link navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Book", books_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%= current_user.name %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Profile" , users_show_path, class: "dropdown-item"%>
                <div class="dropdown-divider"></div>
                <%= link_to "Sign out" , destroy_user_session_path, method: :delete, class: "dropdown-item"%>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Sign in", new_user_session_path, class: "nav-link"%>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="jumbotron m-5"  >
  <h1 class="display-4">Book Reviewへようこそ</h1>
  <hr class="my-4">
  <p>本についてレビューをするサイトです</p>
  <%= button_to "本一覧をみる", books_path, method: :get ,class: "btn btn-primary btn-lg" %>
</div> 

app/views/users/show.html.erb
<div class="card col-sm-6 mx-auto mt-5">
  <% if @user.avatar.attached? %>
  <%= image_tag @user.avatar, class: "card-img-top" %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><%= @user.name %></h5>
    <h6 class="card-subtitle text-muted"><%= @user.age %>才</h6>
    <p class="card-text"><%= @user.email %></p>
  </div>
</div>